#!/usr/bin/env bash

bin = ´which "$0"´
bin = ´dirname "${bin}"´
bin = ´cd "$bin"; pwd´


DEFAULT_LIBEXEC_DIR = "$bin"/../libexec
HADOOP_LIBEXEC_DIR = ${HADOOP_LIBEXEC_DIR:-$DEFAULT_LIBEXEC_DIR}
if [ -e "${HADOOP_LIBEXEC_DIR}/hadoop-config.sh" ]; then
    . ${HADOOP_LIBEXEC_DIR}/hadoop-config.sh
elif [ -e "${HADOOP_COMMON_HOME}/libexec/hadoop-config.sh" ]; then    
    . "HADOOP_COMMON_HOME"/libexec/hadoop-config.sh
elif [ -e "${HADOOP_HOME}/libexec/hadoop-config.sh" ]; then    
    . "HADOOP_HOME"/libexec/hadoop-config.sh
else
    echo "Hadoop common not found"
    exit
fi







